# Generated by Django 5.0.6 on 2024-05-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderdata", "0002_remove_customer_customer_id_alter_customer_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
