# Generated by Django 5.0.6 on 2024-05-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderdata", "0003_remove_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
