# Generated by Django 5.0.6 on 2024-05-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderdata", "0004_alter_category_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Refund",
        ),
    ]
