# Generated by Django 5.0.6 on 2024-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderdata", "0006_delete_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
